// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yqiobuuylyrdycdwukab.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlxaW9idXV5bHlyZHljZHd1a2FiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjExMjE3NTQsImV4cCI6MjA3NjY5Nzc1NH0.2n27PQaY-df8C7twPDj0zNHHTiqzIIqEiCdVgH3tzQ4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});